# Generated by Django 4.1 on 2022-08-17 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
